import type { Metadata } from "next";
import "./globals.css";
import { TailwindIndicator } from "@/components/tailwind-indicator";
import { Footer } from "@/components/Footer";
import { brandSans, logoMark, logoText } from "./fonts";
import { Navbar21 } from "@/components/navbar21";
import { FloatingCallButton } from "@/components/FloatingCallButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${brandSans.variable} ${logoMark.variable} ${logoText.variable} antialiased`}
      >
        <Navbar21 />
        <FloatingCallButton />
        {children}
        <Footer />
        <TailwindIndicator />
      </body>
    </html>
  );
}
